spring:
  application:
    name: OnlineBidderManagement

  datasource:
    url: jdbc:postgresql://localhost:5432/eproc1
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # Use 'update' for evolving the schema without dropping it
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect  # Correct dialect
      spring:
      jpa:
      open-in-view: false


server:
  port: 9090